/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package spacetraders.model

import spacetraders.model.SystemType._

case class ConnectedSystem(
  /* The symbol of the system. */
  symbol: String,
  /* The sector of this system. */
  sectorSymbol: String,
  `type`: SystemType,
  /* The symbol of the faction that owns the connected jump gate in the system. */
  factionSymbol: Option[String] = None,
  /* Position in the universe in the x axis. */
  x: Int,
  /* Position in the universe in the y axis. */
  y: Int,
  /* The distance of this system to the connected Jump Gate. */
  distance: Int
)

object ConnectedSystemEnums {

}
