/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package spacetraders.api

import spacetraders.model.GetMyAgent200Response
import spacetraders.core.JsonSupport._
import sttp.client3._
import sttp.model.Method

object AgentsApi {

def apply(baseUrl: String = "https://api.spacetraders.io/v2") = new AgentsApi(baseUrl)
}

class AgentsApi(baseUrl: String) {

  /**
   * Fetch your agent's details.
   * 
   * Expected answers:
   *   code 200 : GetMyAgent200Response (Successfully fetched agent details.)
   * 
   * Available security schemes:
   *   AgentToken (http)
   */
  def getMyAgent(bearerToken: String)(
): Request[Either[ResponseException[String, Exception], GetMyAgent200Response], Any] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/my/agent")
      .contentType("application/json")
      .auth.bearer(bearerToken)
      .response(asJson[GetMyAgent200Response])

}
